# Configuração de Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/eventodb
spring.datasource.username=postgres
spring.datasource.password=146357

# Configurações do Hibernate (JPA) para criar tabelas e mostrar o SQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta do servidor (Opcional, mas garante que vai rodar na 8080)
server.port=8080